#!/bin/sh

gpul () {
    
    if [ -z $1 ]; then
        git gpul 
    else
        local current_branch=$(git branch-name)
    
        git checkout $1
        git gpul 
        git checkout $current_branch
    fi
}