cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'
tap 'silinternational/tap'

brew 'coreutils'
brew 'dnsmasq'
brew 'thefuck'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'libtiff'
brew 'libtool'
brew 'youtube-dl'
brew 'ssh-audit'
brew 'maven'
brew 'exa'
brew 'awscli'
brew 'sqlparse'
brew 'telnet'
brew 'jq'
brew 'ecs-deploy'
brew 'tree'

cask 'firefox'
cask 'hipchat'
cask 'iterm2'
cask 'postman'
cask 'skype'
cask 'sourcetree'
cask 'sublime-text'
cask 'transmission'
cask 'vlc'
cask 'keepingyouawake'
cask 'spotify-notifications'
cask 'powershell'
cask 'atom'
cask 'limechat'
